version: "4"
services:
  redis:
    image: redis:alpine
    depends_on:
      - web
  web:
    image: python:3.7-alpine
    volumes:
      - ./python-processing/:/usr/src/app
    working_dir: /usr/src/app
    environment:
      - PYTHONPATH=user/src/app
      - FLASK_APP=app.py
      - FLASK_RUN_HOST=0.0.0.0
      - FLASK_DEBUG=1
    command: sh -c "apk add --no-cache gcc musl-dev linux-headers && pip install -r requirements.txt && flask run"
    ports:
      - "8000:5000"
